spring:
  servlet:
    multipart:
      max-file-size: 10MB   # 限制单个文件最大上传大小
      max-request-size: 10MB # 限制整个请求的最大大小
  profiles:
    active: prod
  mvc:
    dispatch-options-request: true
  application:
    name: DormAdmin
  datasource:
    url: jdbc:mysql://10.21.32.154:3306/gdut_tieba?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: root
    hikari:
      maximum-pool-size: 20
      idleTimeout: 600000
      connectionTimeout: 30000
      maxLifetime: 1800000
server:
  port: 8888
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl